CREATE OR REPLACE FUNCTION f1(i int) RETURNS SETOF RECORD AS $$
SELECT name AS value 
FROM public.brin_table
WHERE id=$1;
$$ LANGUAGE SQL;

CREATE OR REPLACE FUNCTION f2(i int)
RETURNS TEXT AS $$
DECLARE
str RECORD;
BEGIN
SELECT name INTO str FROM public.brin_table WHERE id=$1;
RETURN str;
END;
$$ LANGUAGE plpgsql;
