CREATE OR REPLACE RULE update_t1
AS ON UPDATE TO public.tbl WHERE NEW.id BETWEEN 0 AND 99999
DO INSTEAD UPDATE public.t_1 SET name=NEW.name WHERE id=NEW.id;

CREATE OR REPLACE RULE update_t2
AS ON UPDATE TO public.tbl WHERE NEW.id BETWEEN 100000 AND 199999
DO INSTEAD UPDATE public.t_2 SET name=NEW.name WHERE id=NEW.id;

CREATE OR REPLACE RULE update_t3
AS ON UPDATE TO public.tbl WHERE NEW.id BETWEEN 200000 AND 299999
DO INSTEAD UPDATE public.t_3 SET name=NEW.name WHERE id=NEW.id;

CREATE OR REPLACE RULE update_t4
AS ON UPDATE TO public.tbl WHERE NEW.id BETWEEN 300000 AND 399999
DO INSTEAD UPDATE public.t_4 SET name=NEW.name WHERE id=NEW.id;

CREATE OR REPLACE RULE update_t5
AS ON UPDATE TO public.tbl WHERE NEW.id BETWEEN 400000 AND 499999
DO INSTEAD UPDATE public.t_5 SET name=NEW.name WHERE id=NEW.id;

CREATE OR REPLACE RULE update_t6
AS ON UPDATE TO public.tbl WHERE NEW.id BETWEEN 500000 AND 599999
DO INSTEAD UPDATE public.t_6 SET name=NEW.name WHERE id=NEW.id;

CREATE OR REPLACE RULE update_t7
AS ON UPDATE TO public.tbl WHERE NEW.id BETWEEN 600000 AND 699999
DO INSTEAD UPDATE public.t_7 SET name=NEW.name WHERE id=NEW.id;

CREATE OR REPLACE RULE update_t8
AS ON UPDATE TO public.tbl WHERE NEW.id BETWEEN 700000 AND 799999
DO INSTEAD UPDATE public.t_8 SET name=NEW.name WHERE id=NEW.id;

CREATE OR REPLACE RULE update_t9
AS ON UPDATE TO public.tbl WHERE NEW.id BETWEEN 800000 AND 899999
DO INSTEAD UPDATE public.t_9 SET name=NEW.name WHERE id=NEW.id;

CREATE OR REPLACE RULE update_t10
AS ON UPDATE TO public.tbl WHERE NEW.id BETWEEN 900000 AND 999999
DO INSTEAD UPDATE public.t_10 SET name=NEW.name WHERE id=NEW.id;

CREATE OR REPLACE RULE update_1_any
AS ON UPDATE TO public.tbl WHERE (NEW.id NOT BETWEEN 0 AND 99999) AND (OLD.id BETWEEN 0 AND 999999)
DO INSTEAD  (
INSERT INTO public.tbl VALUES(NEW.id, NEW.name);
DELETE FROM public.t_1 WHERE id=OLD.id;); 

CREATE OR REPLACE RULE update_2_any
AS ON UPDATE TO public.tbl WHERE (NEW.id NOT BETWEEN 100000 AND 199999) AND (OLD.id BETWEEN 100000 AND 199999)
DO INSTEAD  (
INSERT INTO public.tbl VALUES(NEW.id, NEW.name);
DELETE FROM public.t_2 WHERE id=OLD.id;); 

CREATE OR REPLACE RULE update_3_any
AS ON UPDATE TO public.tbl WHERE (NEW.id NOT BETWEEN 200000 AND 299999) AND (OLD.id BETWEEN 200000 AND 299999)
DO INSTEAD  (
INSERT INTO public.tbl VALUES(NEW.id, NEW.name);
DELETE FROM public.t_3 WHERE id=OLD.id;);

CREATE OR REPLACE RULE update_4_any
AS ON UPDATE TO public.tbl WHERE (NEW.id NOT BETWEEN 300000 AND 399999) AND (OLD.id BETWEEN 300000 AND 399999)
DO INSTEAD  (
INSERT INTO public.tbl VALUES(NEW.id, NEW.name);
DELETE FROM public.t_4 WHERE id=OLD.id;); 

CREATE OR REPLACE RULE update_5_any
AS ON UPDATE TO public.tbl WHERE (NEW.id NOT BETWEEN 400000 AND 499999) AND (OLD.id BETWEEN 400000 AND 499999)
DO INSTEAD  (
INSERT INTO public.tbl VALUES(NEW.id, NEW.name);
DELETE FROM public.t_5 WHERE id=OLD.id;); 

CREATE OR REPLACE RULE update_6_any
AS ON UPDATE TO public.tbl WHERE (NEW.id NOT BETWEEN 500000 AND 599999) AND (OLD.id BETWEEN 500000 AND 599999)
DO INSTEAD  (
INSERT INTO public.tbl VALUES(NEW.id, NEW.name);
DELETE FROM public.t_6 WHERE id=OLD.id;);

CREATE OR REPLACE RULE update_7_any
AS ON UPDATE TO public.tbl WHERE (NEW.id NOT BETWEEN 600000 AND 699999 ) AND (OLD.id BETWEEN 600000 AND 699999)
DO INSTEAD  (
INSERT INTO public.tbl VALUES(NEW.id, NEW.name);
DELETE FROM public.t_7 WHERE id=OLD.id;); 

CREATE OR REPLACE RULE update_8_any
AS ON UPDATE TO public.tbl WHERE (NEW.id NOT BETWEEN 700000 AND 799999) AND (OLD.id BETWEEN 700000 AND 799999)
DO INSTEAD  (
INSERT INTO public.tbl VALUES(NEW.id, NEW.name);
DELETE FROM public.t_8 WHERE id=OLD.id;); 

CREATE OR REPLACE RULE update_9_any
AS ON UPDATE TO public.tbl WHERE (NEW.id NOT BETWEEN 800000 AND 899999) AND (OLD.id BETWEEN 800000 AND 899999)
DO INSTEAD  (
INSERT INTO public.tbl VALUES(NEW.id, NEW.name);
DELETE FROM public.t_9 WHERE id=OLD.id;);

CREATE OR REPLACE RULE update_10_any
AS ON UPDATE TO public.tbl WHERE (NEW.id NOT BETWEEN 900000 AND 999999) AND (OLD.id BETWEEN 90000 AND 999999)
DO INSTEAD  (
INSERT INTO public.tbl VALUES(NEW.id, NEW.name);
DELETE FROM public.t_10 WHERE id=OLD.id;);










